### PR TITLE
Initial commit to ignore rebase

### PR DESCRIPTION
**Pull request by debasishdebs**
Signed-off-by: Debasish Kanhar <dekanhar@in.ibm.com>

### CODE REVIEW

**Review by chupman — APPROVED** [review]
I just switched it to put to a newly created 0.1.0 branch. I'm happy to merge this now and we can start to work on the codacy fixes and tests in follow-up PRs

**Comment by FlorianHockmann** [comment]
@chupman Do you want to release directly from the `0.1.0` branch or is that only a feature branch? I'm OK to merge this to a feature branch and then address remaining issues there, but we'll have another review when merging into `master` before the release, right? (The name of the branch makes it sound like a release branch.)

**Comment by chupman** [comment]
@FlorianHockmann would you prefer using `0.0.9` or `initial-pr` instead?

**Review by sjudeng — APPROVED** [review]
@debasishdebs Thanks for your great work on this. And thanks for your patience through the epic review process. I think it's looking really solid.

@chupman I agree a feature branch name like "initial" or something would be good instead of 0.1.0.

**Comment by chupman** [comment]
switched to feature branch `initial`. Since we have 2 approvals I'll merge this after lunch assuming no issues are raised.

**Review by FlorianHockmann — APPROVED** [review]
@debasishdebs Also thanks a lot from my side for working on this and for being so patient during the review process! Starting a completely new library involves a lot of work. That's definitely appreciated and I think that this library brings great value to JanusGraph users.

**Comment by chupman** [comment]
Since we have 3 approvals  I'm going to merge this before I go to lunch :)

**Comment by debasishdebs** [comment]
Really thanks guys @chupman @FlorianHockmann @sjudeng for merging this and moving this forward. Feels so happy seeing the hard work being in a branch already :-)

So, my follow up PRs should be with base as `initial` branch right? I won't create anything into master branch? I'm planning to close out #21, so I'm just wondering should I push directly into `initial` or create a PR from my own branch into `initial` ?

Our next steps going forward would be to close out just essential issues and not all right? So that would effectively mean closing out #22 and #19 . Once they are closed, we merge into `master`, release branch `0.1.0` and then we await for community to close other trivial issues right? Correct me if my understanding of whole workflow is wrong :-)

**Pull request merged**
