### PR TITLE
Adding Initial version of JanusGraph Python Client

### PR DESCRIPTION
**Pull request by debasishdebs**
This is 0.0.9 version. 

TODO:
Move to 1.0.0 & create 1.1.0 versions corresponding to JanusGraph 0.3.0 and Master.
Add docs for "Contributions to Lib"
Add docs "How to create connection"
Update Publish Repo from Test PyPi to PyPi

### CODE REVIEW

**Review by sjudeng — COMMENTED** [review]
Thanks for your work on this and for taking the time to contribute it back. Have you signed the JanusGraph CLA? Also it looks like you're asserting copyright on the files rather than releasing to JanusGraph (e.g. "Copyright 2018 JanusGraph Python Authors")?

**Comment by debasishdebs** [comment]
@sjudeng : Yes, my email address is added to CLA. I did contribute before (docs) for JG 0.3.0 with my official ID (dekanhar@in.ibm.com) . Check commit #d3a75c8  #80682da and both contains "Signed-off-by" with my registered email.

As for Second comment, asserting copyright statement on files, what do you mean by that? Do I need to change my Copyright from JanusGrpah-Python to JanusGraph copyright statements? If so, what are those?

**Comment by sjudeng** [comment]
It looks like one of the commits has email address of d.kanhar@gmail.com instead of dekanhar@in.ibm.com, which is what's in the CLA signers file. In this case you could squash the merge commit with your feature commit and re-push.

Regarding copyright I noticed that many of the files indicate "Copyright 2018 Debasish Kanhar" instead of "Copyright 2018 JanusGraph Python Authors".

**Comment by debasishdebs** [comment]
@sjudeng : Ah got that. Well the commit you are talking about, that is my commit message from a PR in my own branch to master. I'm actually unable to squash it (Using git rebase). I think it will be easier if I just close out this PR, delete the branch on my fork, create new branch with updated Copyright statements, update my primary github ID to IBM ID, and create a new PR here. 

Does this sound good to you?

Also, what all changes will I need to make in Copyright statements? Just change to JanusGraph Python Authors?

**Comment by debasishdebs** [comment]
@sjudeng : Created a new PR with updated CLA signs. Looks like that is approved too. Please have a look at [PR#4](https://github.com/JanusGraph/janusgraph-python/pull/4) and let me know if that's correct.

Also, we can move our review/discussion there. and you can tell me about what all copyright changes needs to be done.

**Comment by pluradj** [comment]
@debasishdebs next time you make the appropriate changes in your branch then do a `git push -f`. I'll close this PR since you've already deleted the original branch.

**Pull request closed without merging**
