### PR TITLE
Initial commit to ignore rebase

### PR DESCRIPTION
**Pull request by chupman**
Signed-off-by: Debasish Kanhar <dekanhar@in.ibm.com>

Squashed all the commits in PR #29 so that we can have a feature branch without any credential information. Once merged we should delete the `initial` feature branch.

If @debasishdebs wants to squash #29 instead I will close this PR.

### CODE REVIEW

**Comment by debasishdebs** [comment]
@chupman : Thanks for making this PR. Looks like you have squahed all commits into one? Thanks for helping out on this man. I was planning to work on it today but seems like you have taken care of it. 

I don't think there is point in again my squashing all commits, and re doing what you have already done. What would be next steps? We should get this PR approved and merged into `initial-pr` branch and then delete the branch `initial` right?

Then we will bring our changes, close out existing issues on `initial-pr` branch and bump it to `master` and release a version of library right?

**Comment by chupman** [comment]
@debasishdebs you are correct. Once this gets another approval I can merge to initial-pr and delete the initial branch. I'll reapply the PRs for README badges and codacy fixes once it merges and then we can access what still needs to be done to merge to master and release.

Also I believe we need to figure out who will own the JanusGraph pypi account. I'm thinking it should be a TSC member, possibly @FlorianHockmann. Hopefully multiple members can have access to the account.

**Review by FlorianHockmann — APPROVED** [review]
> Also I believe we need to figure out who will own the JanusGraph pypi account. I'm thinking it should be a TSC member, possibly @FlorianHockmann. Hopefully multiple members can have access to the account.

Sure, I can create the account and then share the credentials with other TSC members who want to have access and committers who want to perform releases.
You probably want to release from Travis, right? In that case I can also add the password as a secure env variable to the Travis settings.

**Comment by debasishdebs** [comment]
@chupman @FlorianHockmann : Thanks guys for taking this forward. Even I agree some TSC member should be give access for PyPi, and Florian seems the best choice. Let us keep the access limited, and unless someone themselves requests and wants to take up responsibility for releases we can then add those members as well. I would though say (@chupman and Me) who can take up responsibility. What do you say @FlorianHockmann @chupman ?

**Pull request merged**
